---
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
      - default.yml

- name: "Install system packages"
  package:
    name: '{{ system_packages }}'
    use: '{{ ansible_pkg_mgr }}'
    state: present

- name: "Add EPEL repository"
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: "BeeGFS RPM key"
  rpm_key: state=present key=http://www.beegfs.io/release/beegfs_6/gpg//RPM-GPG-KEY-beegfs

- name: "BeeGFS repository configuration"
  copy: src=beegfs-rhel7.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: "Data directory"
  file: path=/data state=directory

# - name: "Install packages"
#   yum:
#     name: ['augeas', 'beegfs-utils']
#     state: present
